# Used for hosting multiple sites with their own DNS name all on the same machine, which DNS name will this server bind to
remote-address: ''
# Port for the production server to listen on
port: 8000
# Maximum duration in seconds that an API call can take before timing out
timeout-time: 60

# SSL configuration
ssl:
  # Use SSL at all
  # NOTE: if you're behind a proxy you should leave this disabled
  use: false
  # Redirect HTTP to HTTPS
  redirect: true
  # Path to the certificate root folder
  cert-root: ''
  # Port for the HTTPS server to run on
  port: 443

# MySQL configuration
mysql:
  # Use MySQL at all
  use: false
  # MySQL connection credentials
  host: localhost
  user: root
  password: ''
  database: my_database
